# build environment
FROM node:19-alpine as build
ENV NODE_VERSION 19.7.0
WORKDIR /app
COPY ./package.json ./
COPY ./pnpm-lock.yaml ./
COPY ./pnpm-workspace.yaml ./
COPY ./server/package.json ./server/
ENV PATH /app/node_modules/.bin:$PATH

# Update npm | Install pnpm | Set PNPM_HOME | Install global packages
RUN npm i -g npm@latest; \
 # Install pnpm
 npm install -g pnpm; \
 pnpm --version; \
 pnpm setup; \
 mkdir -p /usr/local/share/pnpm &&\
 export PNPM_HOME="/usr/local/share/pnpm" &&\
 export PATH="$PNPM_HOME:$PATH"; \
 pnpm bin -g &&\
 # Install dependencies
 pnpm add -g pm2 &&\
 pnpm install

COPY . .
RUN pnpm --filter server run build

EXPOSE 3000
ENV NODE_ENV production
CMD [ "pnpm", "--filter", "server", "run", "prod" ]

# TODOproduction environment
# FROM nginx:stable-alpine
# COPY client/nginx.conf /etc/nginx/conf.d/configfile.template
# COPY --from=build /app/server/dist /usr/share/nginx/html
# ENV PORT 8080
# ENV HOST 0.0.0.0
# EXPOSE 8080
# #CMD ["nginx", "-g", "daemon off;"]
# CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
